<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>ptrun-lint</ToolCommandName>
    <Version>0.4.1</Version>
    <PackageReleaseNotes>
- Fix authorization with PersonalAccessToken
- Bump Directory.Packages.props.xml
    </PackageReleaseNotes>
    <Authors>Henrik Lau Eriksson</Authors>
    <Description>Linter for PowerToys Run community plugins</Description>
    <PackageId>Community.PowerToys.Run.Plugin.Lint</PackageId>
    <PackageProjectUrl>https://github.com/hlaueriksson/Community.PowerToys.Run.Plugin.Lint</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>plugin;plugins;powertoys;microsoft-powertoys;powertoys-run;powertoys-run-plugin</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <NoWarn>NU1903</NoWarn>
  </PropertyGroup>

  <Import Project="../../Analyzers.props" />

  <ItemGroup>
    <None Include="..\..\icon.png" Pack="true" PackagePath="\" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Directory.Packages.props.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="17.14.8" /><!--FIX: Snyk issue https://github.com/hlaueriksson/Community.PowerToys.Run.Plugin.Lint/actions/runs/16253525055/job/45886478269 -->
    <PackageReference Include="Microsoft.CodeAnalysis" Version="4.14.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.14.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <PackageReference Include="NReco.Logging.File" Version="1.2.2" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.50.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>
